### ISSUE TITLE
Formatting stacktrace

### ISSUE THREAD

**Issue by lightning95** [valskalla/odin#137]
I'd like to suggest an enhancement for stack trace formatting:
Option for filtering stack trace by in addition to "stack depth" option, because there are a lot of unnecessary stack messages while using monix.
The format, I'm suggesting, is to have a set of class names, you want to exclude, and filter them out on the step of writing the stack trace.

If you accept the idea, I could implement it myself - it doesn't look like very hard.

**Comment by sergeykolbasov** [comment]
Hi @lightning95 

That sounds like a great feature. Feel free to contribute it as another `ThrowableFormatter` option, I'll support you there

**Comment by sergeykolbasov** [comment]
Closed in #144
