### ISSUE TITLE
Cats Effect 3 support

### ISSUE THREAD

**Issue by kubukoz** [valskalla/odin#271]
Hi! Are you planning to upgrade to Cats Effect 3 soon?

If so, would you rather move everything, maintain two branches for a while, or have a build matrix for both like https://github.com/disneystreaming/weaver-test (or even something else)?

**Comment by kubukoz** [comment]
@sergeykolbasov ping :) I can help with this btw, just need to know the preferred approach

**Comment by iRevive** [comment]
@kubukoz I'm working on CE 3 branch in my spare time. Hopefully, I will finish this weekend.  
I didn't sync these changes with Sergey, therefore your question is still relevant

**Comment by sergeykolbasov** [comment]
Hello everyone 

Yes, the plan was to migrate everything to CE 3 without any matrices. I haven't started anything yet myself, but already excited to see the results of @iRevive work . Thanks for the contribution!

**Comment by kubukoz** [comment]
https://github.com/valskalla/odin/pull/273

**Comment by kubukoz** [comment]
So now that https://github.com/valskalla/odin/pull/273 has been merged, all we need is a release - I'm planning to try out the snapshot in a couple days.
