### ISSUE TITLE
Allow to customize formatter colors?

### ISSUE THREAD

**Issue by gvolpe** [valskalla/odin#394]
I couldn't find a way to customize the formatter colors, but please correct me if I'm wrong, I think it would be a nice to have. WDYT?

---

Not that I want to tweak the colors a lot, only one issue is bothering me, which could probably be addressed separately, as it's simpler. The screenshot of the default colorful formatter shows the log level in a bright white color:

![readme-colorful-logger](https://user-images.githubusercontent.com/2317121/72221238-5c02ab00-3561-11ea-8413-155dc309ecd2.png)

However, I see a very dimmed gray color in my console, and I would like that to change.

![what-i-see](https://i.imgur.com/Lncjg1u.png)

Maybe the README screenshot is outdated? Or it could also be a difference regarding the terminal I use (Alacritty 0.9.0). 

I'm using Odin 0.13.0.

Appreciate your time and feedback 🙏🏽

**Comment by sergeykolbasov** [comment]
Hello @gvolpe 

It purely depends on the theme & interpretation of your terminal.

It's not hard to define your own formatter with the colors of your choice:
https://github.com/valskalla/odin/blob/master/core/src/main/scala/io/odin/formatter/Formatter.scala#L29-L63 you can copy-paste and adjust to your own needs

Cheers

**Comment by gvolpe** [comment]
Any chance **only** the colors could be made configurable? Happy to submit a PR for it. 

We could introduce the concept of "theme" or so. Unfortunately, it's not very ergonomic to duplicate all that code just to change a single color, if we think about it.

**Comment by sergeykolbasov** [comment]
Sure, feel free to submit a PR. I think it should be possible to add an additional parameter to the same function to control colors
