### ISSUE TITLE
Magnolia-based derivation of Render type class

### ISSUE THREAD

**Issue by iRevive** [valskalla/odin#70]
[Magnolia](https://github.com/propensive/magnolia) provides a convenient way of a type class derivation based on the structure of a target.

From my point of view, this functionality can be in a separate module (perhaps `odin-derivation` is the suitable one). 

And several ideas regarding configuration options:
1) Obfuscate field;
2) Hide field;
3) Limit the length of iterable;
4) Show\Hide member names;

Configuration example:

```scala
@render(includeMemberName = true)
final case class ApiConfig(
  uri: String,
  @hidden apiKey: String,
  @secret apiSecret: String,
  @length(2) environments: List[String]
)

val config = ApiConfig("https://localhost:8080", "api-key", "api-secret", List("test", "dev", "pre-prod", "prod"))

println(render"API config $config")
// output:
// API config ApiConfig(uri = https://localhost:8080, apiSecret = <secret>, environment = [test, dev, .. 2 more])
```

If this functionality can be useful, I can work on implementation.

**Comment by sergeykolbasov** [comment]
It could be useful, I agree. It's fine to put it in soon-to-be-delivered `odin-extras` package.
