### ISSUE TITLE
Provide an additional way of logging errors

### ISSUE THREAD

**Issue by iRevive** [valskalla/odin#76]
### The problem

Currently, only subtypes of `Throwable` can be added to the logging context as an error. This approach does not work well with other errors produced by `cats.mtl.ApplicativeHandle`. For example, an error can be described as:
```scala
sealed trait PostgresError
object PostgresError {
  final case class ConnectionTimeout(timeout: FiniteDuration) extends PostgresError
  final case class UnexpectedError(cause: Throwable) extends PostgresError
}

final case class UserValidationError(violations: NonEmptyList[String])

type AppError = PostgresError :+: UserValidationError :+: CNil

final case class RaisedError(error: AppError, errorId: String, position: Position)

type Effect[A] = EitherT[IO, AppError, A]
```

`UserValidationError` does not have any underlying throwable, but `PostgressError.UnexpectedError` has one. And an underlying throwable can be added to the logging context.

### The solution idea 

At this point, I propose to add a new type class:
```scala
trait ThrowableSelect[E] {
  def select(e: E): Option[Throwable]
}
```

Basically `ThrowableSelect` is an `Optional` from [monocle](https://github.com/julien-truffaut/Monocle), but I don't see any reason to add this dependency into the classpath. Plus the name has an obvious meaning. 

And the extension method:
```scala
implicit class LoggerOps[F[_]](private val logger: Logger[F]) extends AnyVal {
  def error[E: ThrowableSelect](message: => String, error: E): F[Unit] =
    ThrowableSelect[E].select(error) match {
      case Some(cause) => logger.error(message, cause)
      case None        => logger.error(message)
    }
}
```

### Usage example

And the usage example:
```scala
object RaisedError {
   implicit val throwableSelectRaisedError: ThrowableSelect[RaisedError] = ???
} 

fa.handleWith[RaisedError] { raisedError: RaisedError => 
  logger.error(render"Execution completed with an error $error", error)
}
```

If it does make sense, it can be a part of the `odin-extras` module. 

WDYT?

**Comment by sergeykolbasov** [comment]
I think it would be okay to change the signature of `Logger` as well, with deprecation cycle for old throwable methods

Something like
```scala
def error[A, E](msg: A, error: E)(implicit render: Render[A], tt: ToThrowable[E]): F[Unit]

trait ToThrowable[E] {
  def throwable(e: E): Throwable
}
```

With default instance for each `T <: Throwable` inside of `ToThrowable` companion object.
Not sure if overriding would work out, but worth to try.

**Comment by sergeykolbasov** [comment]
Also, I don't really feel the logic behind optional throwable as a return type. User logs an error but it never shows up in the logs, that's a weird behavior to me.

**Comment by iRevive** [comment]
> Also, I don't really feel the logic behind optional throwable

It's more about syntax sugar. Something similar to `def error(msg: A, error: Option[E])`, but this could be confusing. Since this scenario is pretty rare we can skip it.

> I think it would be okay to change the signature of Logger as well, with deprecation cycle for old throwable methods

It sounds like a good idea.
