### ISSUE TITLE
Add configuration for Formatter

### ISSUE THREAD

**Issue by iRevive** [valskalla/odin#79]
Currently, there is no way to change only one thing in the predefined formatters (e.g. timestamp format). 
And the whole formatter should be copy-pasted. A configuration can simplify this process.

Configuration options:

### 1) Timestamp format

1) Default - prints timestamp using the default format
2) Pattern - prints timestamp using a custom pattern

Also, I would include milliseconds to the default format, since it's hard to track time in multiple logs produced within one second: 
```scala
p"${msg.timestamp.t.F}T${msg.timestamp.t.T},${msg.timestamp.t.milliOfSecond}"
```

### 2) Exception depth

1) Short - prints the first line of the stack trace
2) Full - prints the full stack trace
3) Fixed - prints the given number of lines of the stack trace

### 3) Length of logger name

1) Full - prints the full logger name
2) Abbreviated - shortens the logger name

Example for Abbreviated(length = 5):
```
logger_name = mainPackage.sub.sample.Bar
abbreviated_name = m.s.s.Bar
```

Configuration ideas are based on http://logback.qos.ch/manual/layouts.html.

**Comment by sergeykolbasov** [comment]
I think having some kind of `FormatterFactory` would be just fine
